name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
   
#     - name: Build the Docker image
#       run: docker build --file Dockerfile --tag kunalk07/myscrapper:${GITHUB_REF##*/} .
    - name: Build
      run: docker build -t kunalk07/scrapper:${GITHUB_REF##*/} .

      
    - name: Docker Push
      run: docker push kunalk07/scrapper:${GITHUB_REF##*/}
