name: Build and scan Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sysdiglabs/dummy-vuln-app-kk:latest
     
    - name: Scan image
      uses: sysdiglabs/scan-action@v3.0.2
      with:
        image-tag: "sysdiglabs/dummy-vuln-app-kk:latest"
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
