name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['dir1', 'dir2'] }

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
   
#     - name: Build the Docker image
#       run: docker build --file Dockerfile --tag kunalk07/myscrapper:${GITHUB_REF##*/} .
    # - name: Build
    #   run: docker build -t kunalk07/scrapper5:${GITHUB_REF##*/} .

    # - name: Docker Push
    #   run: docker push kunalk07/scrapper5:${GITHUB_REF##*/}

    - name: Do something with the matrix value
      working-directory: ${{ matrix.dir }}
      run: docker build -t kunalk07/${{ matrix.dir }}:${GITHUB_REF##*/} .

    - name: Scan current project
      uses: anchore/scan-action@v2
      with:
        path: "."

    - name: Docker Push
      run: docker push kunalk07/${{ matrix.dir }}:${GITHUB_REF##*/}

    # - name: upload Anchore scan SARIF report
    #   uses: github/codeql-action/upload-sarif@v1
    #   with:
    #     sarif_file: ${{ steps.scan.outputs.sarif }}


    
    # - uses: anchore/scan-action@v2
    #   id: scan
    #   with:
    #     image: "kunalk07/scrapper5:${GITHUB_REF##*/}"
    #     acs-report-enable: true
    # - name: upload Anchore scan SARIF report
    #   uses: github/codeql-action/upload-sarif@v1
    #   with:
    #     sarif_file: ${{ steps.scan.outputs.sarif }}
